image: Visual Studio 2017
skip_tags: true

install:
  - set path=c:\Program Files (x86)\WiX Toolset v3.11\bin;%path%
  - |-
      echo export const VERSION = { buildID: '%APPVEYOR_BUILD_ID%', buildVersion: '%APPVEYOR_BUILD_VERSION%', buildNo: '%APPVEYOR_BUILD_NUMBER%', gitHash: '%APPVEYOR_REPO_COMMIT%', gitMessage: '%APPVEYOR_REPO_COMMIT_MESSAGE%', production: true }> src/version.js
  - cat src/version.js
  - npm install

cache:
  - node_modules -> package.json
  - '%AppData%\npm\node_modules'

test_script:

build_script:
  - node --version
  - npm --version
  - npm run build -m
  - npm run package-win
  - ls C:\projects\bangbib\release\bangbib-win32-ia32\
  - C:\projects\bangbib\release\bangbib-win32-ia32\bangbib.exe -v
  - node create-msi.js

artifacts:
  - path: release/msi/bangbib.msi
    name: bangbib

deploy:
  release: v$(appveyor_build_version)
  description: 'Automatisiertes Push-Build. Für aktuelle Änderungen die Commit-Logs anschauen.'
  provider: GitHub
  auth_token:
    secure: xf39YWukS9Xjl8akZBdy3e/7xbl4pQn7qdpsguMuV2JcZkZ4zBj2nyh1D0ooi9pW
  artifact: release/msi/bangbib.msi
  draft: false
  prerelease: false
  on:
    branch: master
