name: Build/release

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1
      - name: Install Node.js, NPM
        uses: actions/setup-node@v1
        with:
          node-version: 13
      - run: npm install
      - run: npm run build -m
      - run: npm run package-win
      - name: Use WIX
        if: matrix.os == 'windows-latest'
        run: |
          $wixToolsetBinPath = ";C:\Program Files (x86)\WiX Toolset v3.11\bin;"
          $env:PATH = $env:PATH + $wixToolsetBinPath
          [Environment]::SetEnvironmentVariable("Path", $env:PATH, [EnvironmentVariableTarget]::Machine)
          if ((Get-Command "light.exe" -ErrorAction SilentlyContinue) -eq $null)
          {
            Write-Host "Unable to find light.exe in your PATH"
          }
          node create-msi.js
      - name: see directory
        run: ls ./release