name: Build/release

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Add WIX TOOLSET topath
        run: echo "::add-path::$WIX"
        if: matrix.os == 'windows-latest'
      - name: Check out Git repository
        uses: actions/checkout@v1
      - name: Install Node.js, NPM
        uses: actions/setup-node@v1
        with:
          node-version: 13
      - run: npm install
      - run: npm run build -m
      - run: npm run package-win
      - run: node create-msi.js
      - name: see directory
        run: ls